@baseUrl=http://localhost:3001

###
POST {{baseUrl}}/auth/add-user
Content-Type: application/json

{
  "email": "ravi-ranjan@mail.com",
  "phoneNumber": "+918989009876",
  "name": "Someone",
  "password": "password"
}

###
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "authId": "IM_USER_20240307-122941648",
  "password": "passwords"
}